# Generated by Django 5.1.6 on 2025-03-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('project', 'parent_folder', 'name')},
        ),
    ]
