# Generated by Django 5.1.6 on 2025-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meeting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
